### PR TITLE
Edge bug fixes

### LINKED ISSUE #29: Interactions:  Fix vertex distortion and vertex locking in MoveEdge
- Vertices distort when moving edges, dylan suggests maybe disabling connected vertex prefabs while moving an edge, it could also be a general scaling issue that happens since the vertex is a child of the edge while holding it (maybe the edge is being scaled down while holding it causing the vertices to flatten?)

- Also should consider whether an edge with locked vertices should still be moveable

### LINKED ISSUE #30: Multiplayer: Synchronize edge movements
- Need to probably create a new custom event just for edge movements which contain all the edge data needed to move both the edge prefab and the corresponding vertices attached to it (since the vertices won't be parented to the edge on others' screens).
- Also account for preventing other players from moving the same edge & the vertices attached to that edge while another player is moving it

### LINKED ISSUE #35: Interactions: Disable Multi-Edge Grabbing & Grabbing Vertex While Moving Edge
- Currently the mesh bugs out when you start grabbing two edges that are connected. It works fine if the edges aren't connected, maybe we can disable all other edges when grabbing or just the connected ones.
- We also want to disable grabbing vertex while moving the edge it's attached to since that also bugs out. (solved by disabling the vertices attached to the edge while holding it)

### PR DESCRIPTION
**Pull request by Rami-J**
closes #35, closes #30, closes #29 (partially, still need to figure out how locked vertices should interact with MoveEdge)

# Changes
- All other edges are locked and colored red when any edge is currently being moved, and the edge movements are synchronized across all networked players
- Vertex distortion is fixed when moving an edge by temporarily disabling its gameobject when parented by the edge and thus are not movable when the edge they're attached to is moving

Also fixed some general multiplayer issues such as making sure the correct controller is being tracked by NetworkPlayer (when the controller switches from grab to raycast and vice-versa)

### CODE REVIEW

**Review by DTilley22 — APPROVED** [review]
Looks good, locking a vertex and then moving an edge while the hand is still close to the vertex causes the material of the vertex to switch to the unhovered/default material while the vertex itself is still locked, I'm not really sure which script needs to be edited to handle that

**Comment by Rami-J** [comment]
> 

This is something to do with the interaction between the MoveEdge and LockVertex scripts. Right now, I'm not taking into account any locked vertices when moving an edge. A temporary fix would be to block moving any edge connected to that locked vertex. Do we want to merge this for now and solve the issue in a separate PR?

**Review by elegs99 — COMMENTED** [review]
Looks good only thing is that having all other edges turn bright red is a little jarring. Can we maybe mess with the transparency or different material?

**Comment by DTilley22** [comment]
> This is something to do with the interaction between the MoveEdge and LockVertex scripts. Right now, I'm not taking into account any locked vertices when moving an edge. A temporary fix would be to block moving any edge connected to that locked vertex. Do we want to merge this for now and solve the issue in a separate PR? @DTilley22
Yeah this can be fixed later.

**Comment by Rami-J** [comment]
@elegs99 Should I just not swap the material of the other edges at all when moving? Or would it be better to have the other edges turn like a lighter gray?

**Pull request merged**
